/**
 * Zero-touch bootstrap — provisions all API keys and services from scratch.
 *
 * Requires BROWSER_USE_API_KEY and AGENTMAIL_API_KEY to be pre-configured
 * (these come with `bip install`). Everything else is self-provisioned.
 *
 * Writes credentials to .env.local (resumable — skips keys that already exist).
 */

import { existsSync, readFileSync, appendFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { getCJCredentials } from "./providers/cj-signup";
import { getAnthropicOrOpenRouterKey } from "./providers/anthropic-signup";
import { getShopifyAdminToken } from "./providers/shopify-token";

const ENV_LOCAL_PATH = join(process.cwd(), ".env.local");

type BootstrapOptions = {
  skipCj?: boolean;
  skipLlm?: boolean;
  skipShopify?: boolean;
  skipX?: boolean;
};

/**
 * Append a key=value to .env.local only if it's not already set.
 * Also sets process.env so subsequent steps can use it immediately.
 */
function appendEnvVar(key: string, value: string): void {
  // Already set in current process — skip
  if (process.env[key]) {
    console.log(`   ${key} already set, skipping`);
    return;
  }

  // Check if it's already in .env.local file
  if (existsSync(ENV_LOCAL_PATH)) {
    const contents = readFileSync(ENV_LOCAL_PATH, "utf-8");
    const regex = new RegExp(`^${key}=`, "m");
    if (regex.test(contents)) {
      console.log(`   ${key} already in .env.local, skipping`);
      return;
    }
  }

  // Ensure file exists
  if (!existsSync(ENV_LOCAL_PATH)) {
    writeFileSync(ENV_LOCAL_PATH, "# Auto-generated by bip bootstrap\n", { mode: 0o600 });
  }

  appendFileSync(ENV_LOCAL_PATH, `${key}=${value}\n`);
  process.env[key] = value;
  console.log(`   ${key} saved to .env.local`);
}

/**
 * Check if a key is already available (in process.env or .env.local).
 */
function hasKey(key: string): boolean {
  if (process.env[key]) return true;

  if (existsSync(ENV_LOCAL_PATH)) {
    const contents = readFileSync(ENV_LOCAL_PATH, "utf-8");
    const regex = new RegExp(`^${key}=.+`, "m");
    return regex.test(contents);
  }

  return false;
}

export async function bootstrap(opts: BootstrapOptions = {}): Promise<void> {
  console.log("\n=== bip bootstrap — zero-touch provisioning ===\n");

  // ── Step 0: Verify platform services ──
  console.log("[0] Checking platform services...");

  if (!process.env.BROWSER_USE_API_KEY) {
    console.error("   BROWSER_USE_API_KEY is not set.");
    console.error("   Run `bip install` first to get platform service keys.");
    process.exit(1);
  }
  console.log("   BROWSER_USE_API_KEY: set");

  if (!process.env.AGENTMAIL_API_KEY) {
    console.error("   AGENTMAIL_API_KEY is not set.");
    console.error("   Run `bip install` first to get platform service keys.");
    process.exit(1);
  }
  console.log("   AGENTMAIL_API_KEY: set");

  const results: Record<string, string> = {};
  const skipped: string[] = [];
  const failed: string[] = [];

  // ── Step 1: CJ Dropshipping ──
  if (opts.skipCj) {
    skipped.push("CJ Dropshipping");
    console.log("\n[1] CJ Dropshipping — skipped (--skip-cj)");
  } else if (hasKey("CJ_EMAIL") && hasKey("CJ_PASSWORD")) {
    skipped.push("CJ Dropshipping");
    console.log("\n[1] CJ Dropshipping — already configured");
  } else {
    console.log("\n[1] CJ Dropshipping — signing up...");
    try {
      const creds = await getCJCredentials();
      if (creds) {
        appendEnvVar("CJ_EMAIL", creds.email);
        appendEnvVar("CJ_PASSWORD", creds.password);
        results["CJ Dropshipping"] = creds.email;
      } else {
        failed.push("CJ Dropshipping");
      }
    } catch (e: any) {
      console.error(`   CJ signup error: ${e?.message ?? e}`);
      failed.push("CJ Dropshipping");
    }
  }

  // ── Step 2: LLM provider ──
  if (opts.skipLlm) {
    skipped.push("LLM provider");
    console.log("\n[2] LLM provider — skipped (--skip-llm)");
  } else if (hasKey("ANTHROPIC_API_KEY") || hasKey("OPENROUTER_API_KEY")) {
    skipped.push("LLM provider");
    console.log("\n[2] LLM provider — already configured");
  } else {
    console.log("\n[2] LLM provider — signing up...");
    try {
      const result = await getAnthropicOrOpenRouterKey();
      if (result) {
        const envKey = result.provider === "openrouter" ? "OPENROUTER_API_KEY" : "ANTHROPIC_API_KEY";
        appendEnvVar(envKey, result.key);
        results["LLM provider"] = `${result.provider} (${envKey})`;
      } else {
        failed.push("LLM provider");
      }
    } catch (e: any) {
      console.error(`   LLM provider error: ${e?.message ?? e}`);
      failed.push("LLM provider");
    }
  }

  // ── Step 3: Shopify store ──
  if (opts.skipShopify) {
    skipped.push("Shopify");
    console.log("\n[3] Shopify store — skipped (--skip-shopify)");
  } else if (hasKey("SHOPIFY_SHOP_DOMAIN") && hasKey("SHOPIFY_ACCESS_TOKEN")) {
    skipped.push("Shopify");
    console.log("\n[3] Shopify store — already configured");
  } else {
    console.log("\n[3] Shopify store — creating...");
    try {
      const { setupStore } = await import("../shopify/agents/store-setup");
      await setupStore({ storeName: `bip-store-${Date.now()}`, niche: "dropshipping" });

      // Load the store config to extract domain
      const { existsSync: exists, readFileSync: readFile } = await import("node:fs");
      const { join: pathJoin, dirname } = await import("node:path");
      const configPath = pathJoin(
        dirname(new URL(import.meta.url).pathname),
        "..",
        "shopify",
        "config",
        "store.json",
      );

      if (exists(configPath)) {
        const storeConfig = JSON.parse(readFile(configPath, "utf-8"));
        const domain = storeConfig.shopifyUrl
          ?.replace("https://", "")
          ?.replace("http://", "");

        if (domain) {
          appendEnvVar("SHOPIFY_SHOP_DOMAIN", domain);

          // Extract admin token if we have credentials
          if (storeConfig.email && storeConfig.password) {
            console.log("   Extracting Shopify admin API token...");
            const token = await getShopifyAdminToken(
              domain,
              storeConfig.email,
              storeConfig.password,
            );
            if (token) {
              appendEnvVar("SHOPIFY_ACCESS_TOKEN", token);
              results["Shopify"] = `${domain} (with admin token)`;
            } else {
              console.log("   Token extraction failed — you can set SHOPIFY_ACCESS_TOKEN manually");
              results["Shopify"] = `${domain} (no token — set manually)`;
            }
          } else {
            results["Shopify"] = `${domain} (no token — credentials missing)`;
          }
        } else {
          console.log("   Store URL not captured in config");
          failed.push("Shopify");
        }
      } else {
        console.log("   Store config not found after setup");
        failed.push("Shopify");
      }
    } catch (e: any) {
      console.error(`   Shopify setup error: ${e?.message ?? e}`);
      failed.push("Shopify");
    }
  }

  // ── Step 4: X account ──
  if (opts.skipX) {
    skipped.push("X account");
    console.log("\n[4] X account — skipped (--skip-x)");
  } else {
    // X config is stored in shopify/config/x-account.json, not in .env.local
    const { existsSync: exists } = await import("node:fs");
    const { join: pathJoin, dirname } = await import("node:path");
    const xConfigPath = pathJoin(
      dirname(new URL(import.meta.url).pathname),
      "..",
      "shopify",
      "config",
      "x-account.json",
    );

    if (exists(xConfigPath)) {
      skipped.push("X account");
      console.log("\n[4] X account — already configured");
    } else {
      console.log("\n[4] X account — provisioning...");
      try {
        const { setupXAccount } = await import("../shopify/agents/x-setup");
        await setupXAccount();
        results["X account"] = "provisioned";
      } catch (e: any) {
        console.error(`   X account error: ${e?.message ?? e}`);
        failed.push("X account");
      }
    }
  }

  // ── Summary ──
  console.log("\n=== Bootstrap Summary ===\n");

  if (Object.keys(results).length > 0) {
    console.log("Provisioned:");
    for (const [service, detail] of Object.entries(results)) {
      console.log(`  + ${service}: ${detail}`);
    }
  }

  if (skipped.length > 0) {
    console.log(`\nSkipped (already configured or --skip flag):`);
    for (const service of skipped) {
      console.log(`  - ${service}`);
    }
  }

  if (failed.length > 0) {
    console.log(`\nFailed:`);
    for (const service of failed) {
      console.log(`  x ${service}`);
    }
    console.log("\nRe-run bootstrap to retry failed services.");
  }

  if (existsSync(ENV_LOCAL_PATH)) {
    console.log(`\nCredentials saved to: ${ENV_LOCAL_PATH}`);
  }

  console.log("");
}
